package io.github.onlyashd.hukiawards.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLightMediumContrast = Color(0xFF433500)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF816B1C)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF3E351B)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF776C4D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF1E3D26)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF54755A)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F0)
val onBackgroundLightMediumContrast = Color(0xFF1E1B13)
val surfaceLightMediumContrast = Color(0xFFFFF8F0)
val onSurfaceLightMediumContrast = Color(0xFF141109)
val surfaceVariantLightMediumContrast = Color(0xFFEBE2CF)
val onSurfaceVariantLightMediumContrast = Color(0xFF3B3629)
val outlineLightMediumContrast = Color(0xFF585244)
val outlineVariantLightMediumContrast = Color(0xFF736C5E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF343027)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF8F0E2)
val inversePrimaryLightMediumContrast = Color(0xFFE0C46D)
val surfaceDimLightMediumContrast = Color(0xFFCDC6B9)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F0)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFBF3E5)
val surfaceContainerLightMediumContrast = Color(0xFFEFE7DA)
val surfaceContainerHighLightMediumContrast = Color(0xFFE4DCCE)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD8D1C3)
